export function distorcaoNoHover(imagens) {
  if (!matchMedia('(hover: hover) and (pointer: fine)').matches || matchMedia('(prefers-reduced-motion: reduce)').matches) return null;
  const lista=Array.from(imagens||[]).filter(x=>x instanceof HTMLImageElement); if(!lista.length)return null;
  const canvas=document.createElement('canvas'); canvas.setAttribute('aria-hidden','true'); Object.assign(canvas.style,{position:'fixed',pointerEvents:'none',zIndex:'2147483000',display:'none'}); document.body.appendChild(canvas);
  let gl;try{gl=canvas.getContext('webgl',{alpha:true,antialias:false,powerPreference:'low-power'});}catch(_){gl=null;}if(!gl){canvas.remove();document.documentElement.classList.add('sem-webgl');return null;}
  const vs=`attribute vec2 a;varying vec2 v;void main(){v=a*.5+.5;gl_Position=vec4(a,0.,1.);}`;
  const fs=`precision mediump float;varying vec2 v;uniform sampler2D tex;uniform vec2 cursor;uniform float strength;uniform float aspect;uniform vec2 crop;uniform float cover;
void main(){vec2 p=v;float d=length(vec2((p.x-cursor.x)*aspect,p.y-cursor.y));float pulse=exp(-d*10.)*sin(d*38.-strength*8.)*strength*.018;p+=normalize(vec2((p.x-cursor.x)*aspect,p.y-cursor.y)+.0001)*pulse;vec2 q=p;if(cover>.5){if(crop.x>crop.y){float h=crop.y/crop.x;q.y=(q.y-.5)*h+.5;}else{float w=crop.x/crop.y;q.x=(q.x-.5)*w+.5;}}gl_FragColor=texture2D(tex,q);}`;
  function compile(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error();return s;}
  let prog,buf,texture;try{prog=gl.createProgram();gl.attachShader(prog,compile(gl.VERTEX_SHADER,vs));gl.attachShader(prog,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error();buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);texture=gl.createTexture();}catch(_){canvas.remove();document.documentElement.classList.add('sem-webgl');return null;}
  let active=null, strength=0,target=0,frame=0,dead=false, rect=null, cursor=[.5,.5];const loc={a:gl.getAttribLocation(prog,'a'),tex:gl.getUniformLocation(prog,'tex'),cursor:gl.getUniformLocation(prog,'cursor'),strength:gl.getUniformLocation(prog,'strength'),aspect:gl.getUniformLocation(prog,'aspect'),crop:gl.getUniformLocation(prog,'crop'),cover:gl.getUniformLocation(prog,'cover')};
  function render(){if(dead)return;strength+=(target-strength)*.14;if(rect&&active){const d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.max(1,Math.round(rect.width*d));canvas.height=Math.max(1,Math.round(rect.height*d));gl.viewport(0,0,canvas.width,canvas.height);gl.useProgram(prog);gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.enableVertexAttribArray(loc.a);gl.vertexAttribPointer(loc.a,2,gl.FLOAT,false,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,active);gl.uniform1i(loc.tex,0);gl.uniform2f(loc.cursor,cursor[0],cursor[1]);gl.uniform1f(loc.strength,strength);gl.uniform1f(loc.aspect,rect.width/rect.height);gl.uniform2f(loc.crop,active.naturalWidth,active.naturalHeight);gl.uniform1f(loc.cover,getComputedStyle(active).objectFit==='cover'?1:0);gl.drawArrays(gl.TRIANGLE_STRIP,0,4);}
    if(target>0||strength>.004)frame=requestAnimationFrame(render);else{frame=0;if(!active)canvas.style.display='none';}}
  function start(){if(!frame)frame=requestAnimationFrame(render);}function enter(e){active=e.currentTarget;target=1;canvas.style.display='block';update(e);start();}function update(e){if(!active)return;rect=active.getBoundingClientRect();Object.assign(canvas.style,{left:`${rect.left}px`,top:`${rect.top}px`,width:`${rect.width}px`,height:`${rect.height}px`});cursor=[(e.clientX-rect.left)/Math.max(rect.width,1),1-(e.clientY-rect.top)/Math.max(rect.height,1)];start();}function leave(){target=0;active=null;start();}
  for(const img of lista){img.addEventListener('pointerenter',enter);img.addEventListener('pointermove',update);img.addEventListener('pointerleave',leave);}
  const reposition=()=>{if(active){rect=active.getBoundingClientRect();Object.assign(canvas.style,{left:`${rect.left}px`,top:`${rect.top}px`,width:`${rect.width}px`,height:`${rect.height}px`});}};window.addEventListener('scroll',reposition,true);window.addEventListener('resize',reposition);
  return{destruir(){if(dead)return;dead=true;if(frame)cancelAnimationFrame(frame);for(const img of lista){img.removeEventListener('pointerenter',enter);img.removeEventListener('pointermove',update);img.removeEventListener('pointerleave',leave);}window.removeEventListener('scroll',reposition,true);window.removeEventListener('resize',reposition);gl.deleteTexture(texture);gl.getExtension('WEBGL_lose_context')?.loseContext();canvas.remove();}};
}
